sonar.projectKey=John361_vault-secrets
sonar.organization=john361
sonar.sources=.
sonar.exclusions="**/target/**,**/venv/**,**/node_modules/**,**/*.pb.go"
sonar.rust.clippy.report_path=clippy.json
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.terraform.docker.reportPaths=*
