#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
    CREATE USER ${TERRAFORM_DB_USER} WITH ENCRYPTED PASSWORD '${TERRAFORM_DB_PASSWORD}';
    CREATE DATABASE ${TERRAFORM_DB_NAME};
    ALTER DATABASE ${TERRAFORM_DB_NAME} OWNER TO ${TERRAFORM_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${TERRAFORM_DB_NAME} TO ${TERRAFORM_DB_USER};
EOSQL
