name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          toolchain: "stable"
          components: clippy, rustfmt

      - name: Rust cache
        uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16

      - name: Run cargo check
        run: cargo check --all-targets --all-features

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo test
        run: cargo test --release --all-targets --all-features --verbose

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@2cffc4b4c60ac87a35cdaa3c6e07485503492827
        with:
          tflint_version: v0.64.0
          tflint_config_path: ops/terraform/libs/.tflint.hcl
          cache: true

      - name: Run TFLint
        run: |
          tflint --config=$(pwd)/ops/terraform/libs/.tflint.hcl --init
          tflint --config=$(pwd)/ops/terraform/libs/.tflint.hcl --recursive --format=compact --chdir=ops/terraform/libs --minimum-failure-severity=notice --no-color

  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@8c1d96b76d445fd2e41475a3f0b63dcd1d9cc077
        with:
          tg_version: "1.1.3"
          tofu_version: "1.12.6"

      - name: Run Terragrunt
        run: |
          cd ops/terraform/modules
          terragrunt hcl fmt --check

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@751276eafca55f10f252026015f43c488f2322ba
        with:
          python-version: "3.14"

      - name: Setup uv
        uses: astral-sh/setup-uv@19b4d1e990bec64818914c40230bde93a0de300b
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          working-directory: "ops/scripts/python"

      - name: Install python dependencies
        run: |
          uv sync --project ops/scripts/python --frozen --no-build

      - name: Run python linter
        run: |
          cd ops/scripts/python
          uv run --frozen --no-build ruff check --output-format=github .

      - name: Run python formatting check
        run: |
          cd ops/scripts/python
          uv run --frozen --no-build ruff format --check

      - name: Run python tests
        run: |
          cd ops/scripts/python
          uv run --frozen --no-build pytest --cov=vault_init_credentials --cov-report=term-missing --cov-report=xml
