name: Release

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "The version to deploy"
        required: true

permissions:
  contents: write
  id-token: write
  actions: write
  pages: write

jobs:
  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          toolchain: "stable"

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build .deb package
        run: cargo deb

      - name: Upload Release Asset
        uses: softprops/action-gh-release@e5ee6bc58a36b838b92fc1217f2e4b414b5abcc8
        with:
          files: target/debian/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup APT repository directory
        run: |
          mkdir -p public/conf
          cat << 'EOF' > public/conf/distributions
          Origin: Vault Secrets GitHub Pages
          Label: Vault Secrets APT repository
          Codename: stable
          Architectures: amd64 source
          Components: main
          Description: Vault Secrets APT repository
          SignWith: yes
          EOF

      - name: Import GPG key and generate APT Repo
        run: |
          sudo apt update && sudo apt install -y reprepro gnupg
          echo "${{ secrets.PRIVATE_GPG_KEY }}" | gpg --import --batch
          GPG_KEY_ID=$(gpg --list-secret-keys --with-colons | grep "^sec" | cut -d: -f5)
          echo "Using GPG Key ID: ${GPG_KEY_ID}"
          sed -i "s/SignWith: yes/SignWith: ${GPG_KEY_ID}/" public/conf/distributions
          reprepro -b public -S utils includedeb stable target/debian/*.deb
          cp vault-secrets.gpg public/

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@98ef48e41587a300b82de4cf298aa98b57b2faae
        with:
          path: "public"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@5e98f10ce206463e411e82ac66ef0f2df79c5499
