name: SonarCloud analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Install Rust toolchain & Clippy
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          components: clippy
          toolchain: "stable"

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarqube-scan-action@ad8210318ac8bb816e41990d5af2b304f7a6c213
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
