name: SonarCloud analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Rust toolchain & Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=John361_vault-secrets
            -Dsonar.organization=john361
            -Dsonar.sources=.
            -Dsonar.exclusions=**/target/**, **/venv/**, **/node_modules/**, **/*.pb.go
            -Dsonar.rust.clippy.report_path=clippy.json
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.terraform.docker.reportPaths=*
          projectBaseDir: .
