services:
  vault:
    image: hashicorp/vault:2.0
    container_name: "vault"
    hostname: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config/config.hcl:/vault/config/vault.hcl:ro
      - ./data/vault:/data/vault
    restart: no
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 10s
    command: server
    cap_add:
      - IPC_LOCK
