services:
  vault:
    image: hashicorp/vault:2.0
    container_name: "vault"
    hostname: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config/config.hcl:/vault/config/vault.hcl:ro
      - ./data/vault:/data/vault
    restart: no
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 10s
    command: server
    cap_add:
      - IPC_LOCK

  postgres:
    image: postgres:18.4-alpine
    container_name: "postgres"
    hostname: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Indian/Reunion
      LANG: fr_FR.utf8
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./postgres/scripts:/docker-entrypoint-initdb.d:ro
    restart: no
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${TERRAFORM_DB_NAME} -U $${TERRAFORM_DB_USER}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 10s
